    name: cinetandem
    description: A new Flutter project.
    publish_to: 'none'
    version: 1.0.0+1

    environment:
        sdk: ">=3.0.0 <4.0.0"

    dependencies:
        flutter:
            sdk: flutter
        http: ^1.2.1
        cached_network_image: ^3.3.1
        carousel_slider: ^5.0.0
        flip_card: ^0.7.0
        shared_preferences: ^2.2.3
        flutter_secure_storage: ^9.2.2
        cupertino_icons: ^1.0.8
        sqflite: ^2.3.3
        video_player: ^2.9.1
        chewie: ^1.7.1
        uuid: ^4.5.0
        image_picker: ^1.0.7
        share_plus: ^10.0.2
        intl: ^0.20.0
        timeago: ^3.7.0
        shimmer: ^3.0.0
        marquee: ^2.2.3
        font_awesome_flutter: ^10.7.0
        url_launcher: ^6.3.0
        screen_brightness: ^0.2.2
        flutter_volume_controller: ^1.2.0
        webview_flutter: ^4.9.0
        email_validator: ^2.1.17
        flutter_cache_manager: ^3.3.2
        google_fonts: ^6.2.1
        audioplayers: ^6.0.0
        provider: ^6.1.2
        equatable: ^2.0.5
        flutter_dotenv: ^5.1.0
        go_router: ^10.0.0


    dev_dependencies:
        flutter_test:
            sdk: flutter
        flutter_lints: ^4.0.0

    flutter:
        uses-material-design: true
        assets:
            - .env
